### ISSUE TITLE
Type check tycheck folder

### ISSUE THREAD

**Issue by albsch** [etylizer/etylizer#6]
Checked against `e508a67`

🕑 = timeout
⚡ = correctness error, unknown blame
🚧 = implementation missing
🌏 = typing algorithm error

* [x] `check_if.erl`
* [x] `check_if_fail.erl`
* [x] `concat.erl`
* [x] `concat_fail.erl`
* [ ] `filtermap.erl` 🕑 (#105)
* [ ] `filtermap_fail1.erl` 🕑 (#105)
* [ ] `filtermap_fail2.erl` 🕑 (#105)
* [ ] `filtermap_fail3.erl` 🕑 (#105)
* [ ] `flatten.erl` 🚧 (support for named types missing #94)
* [ ] `hlist.erl` 🚧 (needs extension to Erlang's type language)
* [ ] `hlist_fail.erl` 🚧 (needs extension to Erlang's type language)
* [ ] `if_refine.erl` 🚧 (#5)
* [x] `if_refine_fail1.erl`
* [ ] `map_even2.erl` 🚧 (maps not implemented #94)
* [ ] `map_even.erl` 🚧 (maps not implemented #94)
* [ ] `map_even_fail.erl` 🚧 (maps not implemented #94)
* [ ] `match.erl` ⚡ (#106)
* [x] `match_fail.erl`
* [x] `my_and.erl`
* [ ] `my_and_fail.erl` 🕑 (#107)
* [x] `overloaded_fun2.erl` ⚡
* [x] `overloaded_fun.erl` 
* [x] `overloaded_fun_fail1.erl`
* [x] `pattern_refine.erl`
* [ ] `recursive.erl` 🕑 
* [ ] `typecase.erl` 🚧 (named types #94)
* [ ] `typecase_fail.erl` 🚧 (named typed #94)
* [x] `union_distrib.erl`
* [x] `union_distrib_fail.erl`
* [ ] `union.erl` 🚧 (named typed #94)
* [ ] `union_fail.erl` 🚧 (named typed #94)

**Comment by albsch** [comment]
Closing in favor of single issues.
